CREATE TABLE IF NOT EXISTS master.Tb_Categories
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    display_order integer NOT NULL,
    CONSTRAINT Tb_Categories_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS master.Tb_Categories
    OWNER to postgres;