CREATE TABLE IF NOT EXISTS master.Tb_Categories
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    display_order integer NOT NULL,
    CONSTRAINT Tb_Categories_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS master.Tb_Products
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),

    title VARCHAR(255) NOT NULL,
    description TEXT,

    isbn VARCHAR(50) NOT NULL,
    author VARCHAR(255) NOT NULL,

    list_price NUMERIC(10,2) NOT NULL CHECK (list_price BETWEEN 1 AND 10000),
    price NUMERIC(10,2) NOT NULL CHECK (price BETWEEN 1 AND 10000),
    price50 NUMERIC(10,2) NOT NULL CHECK (price50 BETWEEN 1 AND 10000),
    price100 NUMERIC(10,2) NOT NULL CHECK (price100 BETWEEN 1 AND 10000)
);


ALTER TABLE IF EXISTS master.tb_products ADD CONSTRAINT uq_books_isbn UNIQUE (isbn);

ALTER TABLE IF EXISTS master.Tb_Categories
    OWNER to postgres;

ALTER TABLE IF EXISTS master.Tb_Products
    OWNER to postgres;

ALTER TABLE master.tb_products ADD COLUMN category_id integer;
ALTER TABLE master.tb_products ADD CONSTRAINT fk_products_categories FOREIGN KEY (category_id) REFERENCES master.tb_categories(id) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE master.tb_products ADD COLUMN image_url text;


CREATE TABLE IF NOT EXISTS master.Tb_Companies
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),

    name VARCHAR(255) NOT NULL,
    address TEXT,
    city TEXT,
    state TEXT,
    postalcode TEXT,
    phonenumber TEXT
);
