CREATE TABLE IF NOT EXISTS master.Tb_Categories
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    display_order integer NOT NULL,
    CONSTRAINT Tb_Categories_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS master.Tb_Products
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),

    title VARCHAR(255) NOT NULL,
    description TEXT,

    isbn VARCHAR(50) NOT NULL,
    author VARCHAR(255) NOT NULL,

    list_price NUMERIC(10,2) NOT NULL CHECK (list_price BETWEEN 1 AND 10000),
    price NUMERIC(10,2) NOT NULL CHECK (price BETWEEN 1 AND 10000),
    price50 NUMERIC(10,2) NOT NULL CHECK (price50 BETWEEN 1 AND 10000),
    price100 NUMERIC(10,2) NOT NULL CHECK (price100 BETWEEN 1 AND 10000)
);


ALTER TABLE IF EXISTS master.tb_products ADD CONSTRAINT uq_books_isbn UNIQUE (isbn);

ALTER TABLE IF EXISTS master.Tb_Categories
    OWNER to postgres;

ALTER TABLE IF EXISTS master.Tb_Products
    OWNER to postgres;

ALTER TABLE master.tb_products ADD COLUMN category_id integer;
ALTER TABLE master.tb_products ADD CONSTRAINT fk_products_categories FOREIGN KEY (category_id) REFERENCES master.tb_categories(id) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE master.tb_products ADD COLUMN image_url text;


CREATE TABLE IF NOT EXISTS master.Tb_Companies
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),

    name VARCHAR(255) NOT NULL,
    address TEXT,
    city TEXT,
    state TEXT,
    postalcode TEXT,
    phonenumber TEXT
);


ALTER TABLE master.tb_products
ADD CONSTRAINT pk_tb_products PRIMARY KEY (id);


CREATE TABLE IF NOT EXISTS master.tb_shoppingcart
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    product_id integer NOT NULL,
    product_count integer NOT NULL,
    application_user_id text NOT NULL,
    CONSTRAINT fk_tb_shoppingcart_tb_products FOREIGN KEY (product_id)
        REFERENCES master.tb_products (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE RESTRICT
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS master.tb_shoppingcart
    OWNER to postgres;


ALTER TABLE master.tb_shoppingcart
ADD CONSTRAINT pk_tb_shoppingcart PRIMARY KEY (id);


ALTER TABLE master.Tb_Companies ADD CONSTRAINT pk_Tb_Companies PRIMARY KEY (id);

CREATE TABLE  IF NOT EXISTS master.tb_order_headers
(
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    application_user_id TEXT NOT NULL,

    order_date           TIMESTAMP NOT NULL,
    shipping_date        TIMESTAMP,

    order_total          DOUBLE PRECISION NOT NULL,

    order_status         VARCHAR(50),
    payment_status       VARCHAR(50),

    tracking_number      VARCHAR(100),
    carrier              VARCHAR(100),

    payment_date         TIMESTAMP,
    payment_due_date     DATE,

    payment_id           VARCHAR(100),

    phone_number         VARCHAR(20) NOT NULL,
    address              TEXT NOT NULL,
    city                 VARCHAR(100) NOT NULL,
    state                VARCHAR(100) NOT NULL,
    postal_code           VARCHAR(20) NOT NULL,
    name                 VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS master.tb_order_details
(
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_header_id  INT NOT NULL,
    product_id       INT NOT NULL,

    count            INT NOT NULL,
    price            DOUBLE PRECISION NOT NULL
);

ALTER TABLE master.tb_order_details ADD CONSTRAINT fk_order_details_header FOREIGN KEY (order_header_id) REFERENCES master.tb_order_headers(id) ON DELETE CASCADE;
ALTER TABLE master.tb_order_details ADD CONSTRAINT fk_order_details_product FOREIGN KEY (product_id) REFERENCES master.tb_products(id) ON DELETE RESTRICT;